# Generated by Django 5.1.6 on 2025-04-23 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_category_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyFollow',
            new_name='Follow',
        ),
        migrations.RemoveField(
            model_name='companycomment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companycomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recruitmentapply',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='recruitmentapply',
            name='resume',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='skills_required',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Default'), (1, 'Accepted'), (2, 'Rejected')], default=(0, 'Default'))),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.recruitment')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CandidateComment',
        ),
        migrations.DeleteModel(
            name='CompanyComment',
        ),
        migrations.DeleteModel(
            name='RecruitmentApply',
        ),
    ]
