# Generated by Django 5.1.6 on 2025-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_rename_companyfollow_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Employer')], default=0),
        ),
    ]
