# Generated by Django 5.1.6 on 2025-04-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_apply_status_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='icon',
        ),
    ]
